pipeline {

    agent any


    environment {
        DOCKERHUB_USERNAME = 'doramar97'
        DOCKERHUB_PASSWORD = credentials('my-docker-pass')
        DOCKERHUB_REPO = 'november'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        NODE  =  "${env.NODE_NAME}"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'example', url: 'https://github.com/dor-amar/jenkins.git'
            }
        }


        stage('Build Docker Image') {
            steps {
                sh '''
                   cd ci-pipeline
                   sudo docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
                '''
            }
        }
 
    }
}



