pipeline {

    agent any


    environment {
        DOCKERHUB_USERNAME = 'doramar97'
        DOCKERHUB_PASSWORD = credentials('my-docker-pass')
        DOCKERHUB_REPO = 'november'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                   cd ci-pipeline
                   docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG .
                '''
            }
        }

        stage('Login to Docker Hub') {
            steps {
                sh '''
                   echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
                '''
            }
        }

    }
}



