pipeline {
  agent any

  stages {

    stage('Build') {
      steps {
        echo 'Building Docker Image With November Class'
        // Build the docker image and push it to docker hub
      }
    }
  }
}