pipeline {
  agent { label 'worker' }


  environment {
    DOCKER_CREDENTIALS = credentials('docker-cred')

  }
  
  stages {
    stage('Checkout Git repository') {
        steps {
            git branch: 'main', url: 'https://github.com/dor-amar/jenkins.git'
        }
    }
    stage('Build Docker image') {
        steps {
            script {
                dir('november') {
                    sh "docker build -t doramar97/my-app-nov:latest ."
                }

            }
        }
    }
    stage('Login to Docker') {
        steps {
            script {
                sh "echo ${DOCKER_CREDENTIALS_PSW} | docker login -u ${DOCKER_CREDENTIALS_USR} --password-stdin"
            }
        }
    }
    stage('Push Docker Image') {
        steps {
            script {
                sh "docker push doramar97/my-app-nov:latest"
            }
        }
    }
    // stage('Deployment') {
    //     steps {
            
    //     }
    // }

  }

}